DOCNAME=mcca-slides
SRC=$(DOCNAME).tex Makefile
TEXC=pdflatex

$(DOCNAME).pdf: $(SRC)
	$(TEXC) $^
	$(TEXC) $^
clean:
	rm -f \
$(DOCNAME).aux \
$(DOCNAME).dvi \
$(DOCNAME).log \
$(DOCNAME).nav \
$(DOCNAME).out \
$(DOCNAME).snm \
$(DOCNAME).toc \
$(DOCNAME).dvi \
$(DOCNAME).pdf \
$(DOCNAME).ps \
$(DOCNAME).vrb \
texput.log \
